package com.example.feature_film_info.enums

internal enum class SiteType(
    val title:String
) {
    IMDb("IMDb"),
    THE_MOVIE_DB("The Movie Database"),
    ROTTEN_TOMATOES("Rotten Tomatoes"),
    METACRITIC("Metacritic"),
    NETFLIX("Netflix"),
    GOOGLE_PLAY("Google Play"),
    FILM_AFFINITY("Film Affinity"),
    FREEBASE("Freebase"),
    GND("Gnd"),
    VIAF("viaf"),
    ALLO_CINE("Allo Cine"),
    ALL_MOVIE("All Movie"),
    PORT("Port"),
    DNF("Dnf"),
    MOVIE_METER("Movie Meter"),
    BOX_OFFICE_MOJO("Box Office Mojo"),
    CSFD("Csfd"),
    KINENOTE("Kinenote"),
    ALL_CINEMA("Allcinema"),
    KINOPOISK("Kinopoisk"),
    ELONET("Elonet"),
    LDI_F("Ldi F"),
    CINEPLEX("Cineplex"),
    E_DB("E Db"),
    EL_CINEMA("El Cinema"),
    SCOPE_DK("Scope Dk"),
    SWEDISH_FILM_DATABASE_FILM("Swedish Film Database Film"),
    EL_FILM("El Film"),
    OF_DB("Of Db"),
    OPEN_MEDIA_DATABASE("Open Media Database"),
    QUORA_TOPIC("Quora Topic"),
    CINEMA_DE("Cinema De"),
    DEUTSCHE_SYNCHRONKARTEI("Deutsche Synchronkartei"),
    MOVIE_WALKER("Movie Walker"),
    TV_GUIDE("TV Guide"),
    FILM_WEB_PL("Film Web PL"),
    TV_COM("TV Com"),
    ISAN("Isan"),
    EIDR("Eidr"),
    AFI_CATALOG_OF_FEATURE("Afi Catalog Of Feature"),
    THE_NUMBERS("The Numbers"),
    TCM_MOVIE_DATABASE("Tcm Movie Database"),
    CINE_GR("Cine Gr"),
    BFI_NATIONAL_ARCHIVE("Bfi National Archive"),
    EXPLOITATION_VISA("Exploitation Visa"),
    SRATIM("sratim"),
    CINE_RESSOURCES("Cine Ressources"),
    CINEMATHEQUE_QUEBECOISE("cinematheque Quebecoise"),
    ENCYCLOPAEDIA_BRITANNICA_ONLINE("Encyclopaedia Britannica Online"),
    BECHDEL_TEST_MOVIE_LIST("Bechdel Test Movie List"),
    MOVIEPLAYER_IT("Movieplayer It"),
    M_YMOVIES("Mymovies.it"),
    CINEMATOGRAFO("Cinematografo"),
    LUMIERE("Lumiere"),
    BFI("Bfi"),
    PRISMA("Prisma"),
    CINE_MAGIA("Cine Magia"),
    DAUM("Daum"),
    DOUBAN("Douban"),
    MUSEUM_OF_MODERN_ART("Museum Of Modern Art"),
    IL_MONDO_DEI_DOPPIATORI("Il Mondo Dei Doppiatori"),
    FANDANGO("Fandango"),
    MOVIEPILOT_DE("Moviepilot De"),
    SUDOC_AUTHORITIES("Sudoc Authorities"),
    BIBLIOTHEQUE_NATIONALE_DE_FRANCE("Bibliotheque Nationale De France"),
    SIAMZONE("Siamzone"),
    ACADEMY_AWARDS_DATABASE("Academy Awards Database"),
    KNOW_YOUR_MEME("know Your Meme"),
    THE_ENCYCLOPEDIA_OF_SCIENCE_FICTION("The Encyclopedia Of Science Fiction"),
    LETTERBOXD("Letterboxd"),
    COMIC_VINE("Comic Vine"),
    THE_TVDB("The TVDB"),
    TV_SPIELFILM_SERIES("Tv Spielfilm Series")
}